### ISSUE TITLE
[ Erro Documentação ] - 1.3 Especificação dos Casos de Uso

### ISSUE THREAD

**Issue by PedroHBLB** [PedroHBLB/Source-Code-Inspection#1]
### **Introdução**

Na documentação, especificamente no item 1.3.1 "CSU01 – Inserir dinheiro", há um erro na tabela do Fluxo Principal, na coluna "Ações do Sistema", item 3: "O Sistema valida a nota de papel-moeda inserida".

### **Descrição do Erro**

A documentação não especifica quais notas são válidas para inserção na máquina. Essa informação é essencial para garantir que os usuários saibam quais denominações podem ser aceitas.

**Comment by glopez337** [comment]
### **Resolução**

Para resolver essa questão, é fundamental listar as notas válidas para inserção de forma detalhada. Isso ajudará a evitar qualquer mal-entendido sobre a funcionalidade descrita no item, garantindo que os usuários saibam exatamente quais denominações são aceitas pela máquina.

**Comment by PedroHBLB** [comment]
Obrigado pela resposta! Concordo que listar as notas válidas de forma detalhada é essencial para evitar mal-entendidos. Vou implementar essa alteração na documentação.
