### ISSUE TITLE
[ Erro Documentação ] - 1.3 Especificação dos Casos de Uso

### ISSUE THREAD

**Issue by PedroHBLB** [PedroHBLB/Source-Code-Inspection#2]
### **Introdução**

Na documentação, especificamente no item 1.3.1 "CSU01 – Inserir dinheiro", há um erro na tabela do Fluxo de Exceção 1: 3a. O Sistema não valida a nota de papel-moeda, na coluna "Ações do Sistema", item 2: "Enquanto o Cliente não retirar a nota de papel-moeda, o Sistema informa que a nota de papel-moeda é inválida".

### **Descrição do Erro**

O sistema informa que a nota é inválida, mas não especifica como o sistema lidará com esse erro. A mensagem pode ser interpretada de formas diferentes.

**Comment by glopez337** [comment]
### **Resolução**
Para resolver essa questão, é fundamental especificar como o sistema lidará com o erro, de maneira clara.
