### ISSUE TITLE
[ Erro Documentação ] - 1.3 Especificação dos Casos de Uso #3

### ISSUE THREAD

**Issue by glopez337** [PedroHBLB/Source-Code-Inspection#3]
Introdução
Na documentação, especificamente no item 1.3.2 CSU03 – Solicitar troco, há um erro na tabela do Fluxo Principal 3a. O Sistema zera o valor do saldo.

Descrição do Erro
Como o sistema só pode devolver papel-moeda, não está claro como ele irá zerar o saldo caso reste um valor que não possa ser devolvido apenas em papel-moeda, como por exemplo, R$ 1,00

**Comment by PedroHBLB** [comment]
Você tem razão ao identificar a inconsistência no fluxo descrito no item 1.3.2 CSU03 – Solicitar troco. Realmente, o sistema só deveria zerar o saldo quando consegue devolver o valor integral em papel-moeda. No caso de valores residuais, como R$ 1,00, que não podem ser devolvidos dessa forma, a lógica precisa ser revisada para que o sistema indique o saldo restante de maneira clara.

Vamos corrigir a documentação e revisar o comportamento do sistema para que o saldo não seja zerado indevidamente. Em situações em que restar um valor não passível de devolução em papel-moeda, o sistema poderá, por exemplo, gerar um aviso ao usuário ou oferecer alternativas para a utilização desse saldo.

Mais uma vez, agradecemos por levantar essa questão. Estaremos corrigindo o mais rápido possível!
