### ISSUE TITLE
[ Erro Código ] - Arquivo TicketMachine.java linha 25

### ISSUE THREAD

**Issue by PedroHBLB** [PedroHBLB/Source-Code-Inspection#4]
### **Descrição**

A linha if (papelMoeda[1] == quantia) está errada, pois o índice está fixado em 1, o que sempre compara com o valor 5. O correto seria utilizar o índice i para verificar os diferentes valores possíveis de papel moeda.

**Comment by glopez337** [comment]
Erro corrigido, ok!

**Comment by PedroHBLB** [comment]
Ok, verificado
