### ISSUE TITLE
[ Erro Código ] - Arquivo TicketMachine.java linha 48

### ISSUE THREAD

**Issue by glopez337** [PedroHBLB/Source-Code-Inspection#6]
### **Descrição**

No método imprimir, a variável saldo está sendo exibida em vez de valor. O saldo é o montante inserido, mas o valor do bilhete deveria ser o foco. O que deve ser impresso é o valor da compra, não o saldo.

**Comment by PedroHBLB** [comment]
Erro corrigido

**Comment by glopez337** [comment]
Ok, verificado obrigado
